version: "3"
services:
  db:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    networks:
      - db_net
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      MONGODB_HOST: db
    networks:
      - db_net
networks:
  db_net: