version: "3"
services:
  db:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    restart: always
    networks:
      - db_net
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    restart: always
    environment:
      MONGODB_HOST: db
      MONGODB_DB_NAME: docker_app
      MONGODB_PORT: 27017
    networks:
      - db_net
networks:
  db_net: